---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ephemeron-controller
  namespace: default
automountServiceAccountToken: true

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: control-ephemeron
rules:
  - apiGroups: ["qualified.io"]
    resources: ["ephemerons", "ephemerons/status"]
    verbs:
      - create
      - get
      - patch
      - delete
      - list
      - watch
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs:
      - get
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs:
      - create
      - get
      - list
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ephemeron-controller-binding
subjects:
  - kind: ServiceAccount
    namespace: default
    name: ephemeron-controller
roleRef:
  kind: ClusterRole
  name: control-ephemeron
  apiGroup: rbac.authorization.k8s.io
