[package]
name = "ephemeron"
version = "0.1.0"
authors = ["kazk <kazk.dev@gmail.com>"]
edition = "2018"
default-run = "run"

[dependencies]
kube = { version = "0.53.0", features = ["derive"] }
kube-runtime = "0.53.0"
k8s-openapi = { version = "0.11.0", default-features = false, features = ["v1_20"] }
schemars = { version = "0.8.0", features = ["chrono"] }

serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.62"
serde_yaml = "0.8.17"

snafu = "0.6.10"
futures = "0.3.12"
chrono = "0.4.19"
tracing = "0.1.23"
tracing-futures = "0.2.4"
tracing-subscriber = "0.2.15"
tokio = { version = "1.2.0", features = ["macros", "rt", "rt-multi-thread"] }

warp = "0.3.0"
xid = "1.0.0"
