# Use envsubst to set IMAGE and HOST
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "ephemeron-api-config"
data:
  "config.yml": |
    presets:
      nginx:
        image: "nginx"
        port: 80
        readinessProbe:
          path: /

    # Allowed apps
    apps:
      example: apikey

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ephemeron-api
  namespace: default
  labels:
    app: ephemeron-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ephemeron-api
  template:
    metadata:
      labels:
        app: ephemeron-api
    spec:
      serviceAccountName: ephemeron-api
      containers:
        - name: ephemeron-api
          image: "${IMAGE}"
          env:
            - { name: "RUST_LOG", value: "info,ephemeron=trace" }
            - { name: "EPHEMERON_CONFIG", value: "/app/config/config.yml" }
            - { name: "JWT_SECRET", value: "${JWT_SECRET}" }
          ports:
            - containerPort: 3030
          resources:
            # Adjust these as needed
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
          volumeMounts:
            - { name: "config", mountPath: "/app/config", readOnly: true }
      volumes:
        - name: "config"
          configMap: { name: "ephemeron-api-config" }

---
apiVersion: v1
kind: Service
metadata:
  name: ephemeron-api
  namespace: default
  labels:
    app: ephemeron-api
spec:
  selector:
    app: ephemeron-api
  ports:
    - port: 3030
      targetPort: 3030

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ephemeron-api
  namespace: default
  labels:
    app: ephemeron-api
spec:
  rules:
    - host: "${HOST}"
      http:
        paths:
          - backend:
              service:
                name: ephemeron-api
                port:
                  number: 3030
            path: /
            pathType: Prefix
