---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ephemeron-api
  namespace: default
automountServiceAccountToken: true

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: use-ephemeron
rules:
  - apiGroups: ["qualified.io"]
    resources: ["ephemerons", "ephemerons/status"]
    verbs:
      - create
      - get
      - patch
      - delete
      - list
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ephemeron-api-binding
subjects:
  - kind: ServiceAccount
    namespace: default
    name: ephemeron-api
roleRef:
  kind: ClusterRole
  name: use-ephemeron
  apiGroup: rbac.authorization.k8s.io
