kind: Ephemeron
apiVersion: qualified.io/v1alpha1
metadata:
  name: "example"
spec:
  service:
    image: "nginx"
    port: 80
    readinessProbe:
      path: /
  # Use `envsubst` to set `expirationTime`
  expirationTime: "${EXPIRES}"
